version: "3.7"
services:
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`server.appliedhealthinformatics.com`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt

  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:

  # the parts commented out currently: https://towardsdatascience.com/how-to-deploy-a-secure-api-with-fastapi-docker-and-traefik-b1ca065b100f 
  # https://github.com/ahmedbesbes/fastapi-ssl/blob/main/docker-compose.yaml 